// tslint:disable:no-null-keyword
export const fixtureResponse = {
  kind: 'Listing',
  data: {
    modhash: '',
    dist: 26,
    children: [
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'vancouver',
          selftext:
            'Are you looking for something to do? Would you like to advertise your event? Want to suggest something to everyone? Whether it\'s a show, a play, a conference, a restaurant opening, or whatever, this is where you can stick all of it. This is a monthly post that is useful for Vancouverites, useful for tourists, and useful for the main Vancouver sub.\n\n**New**\n\nPlease post any opportunities to volunteer that you want the subreddit to know about. This thread will be curated periodically to keep the events of the week fresh and visible.\n\n**Who?**\n\nEvents don\'t need to be yours! You\'re welcome to post any interesting/fun/unknown/well known/moderately-enjoyable events. Will remove posts completely off topic (like a link to one\'s unrelated blog or comments about how there\'s nothing to do in this city)\n\n**Tip**\n\nSort the comments below BY NEW to see the latest events\n\n\n[April Events Thread](https://www.reddit.com/r/vancouver/comments/b5dlhh/april_events_and_volunteering_thread_please_post/)',
          author_fullname: 't2_3rnmf',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            'May Events and Volunteering Thread. Please post your upcoming events and volunteering opportunities here.',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/vancouver',
          hidden: false,
          pwls: 6,
          link_flair_css_class: 'grey',
          downs: 0,
          thumbnail_height: null,
          hide_score: false,
          name: 't3_bjcurx',
          quarantine: false,
          link_flair_text_color: 'dark',
          author_flair_background_color: '',
          subreddit_type: 'public',
          ups: 23,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: null,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Ask Vancouver',
          can_mod_post: false,
          score: 23,
          approved_by: null,
          thumbnail: 'self',
          edited: false,
          author_flair_css_class: '',
          author_flair_richtext: [],
          gildings: {},
          content_categories: null,
          is_self: true,
          mod_note: null,
          created: 1556711732.0,
          link_flair_type: 'text',
          wls: 6,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'self.vancouver',
          selftext_html:
            '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Are you looking for something to do? Would you like to advertise your event? Want to suggest something to everyone? Whether it&amp;#39;s a show, a play, a conference, a restaurant opening, or whatever, this is where you can stick all of it. This is a monthly post that is useful for Vancouverites, useful for tourists, and useful for the main Vancouver sub.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;New&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;Please post any opportunities to volunteer that you want the subreddit to know about. This thread will be curated periodically to keep the events of the week fresh and visible.&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Who?&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;Events don&amp;#39;t need to be yours! You&amp;#39;re welcome to post any interesting/fun/unknown/well known/moderately-enjoyable events. Will remove posts completely off topic (like a link to one&amp;#39;s unrelated blog or comments about how there&amp;#39;s nothing to do in this city)&lt;/p&gt;\n\n&lt;p&gt;&lt;strong&gt;Tip&lt;/strong&gt;&lt;/p&gt;\n\n&lt;p&gt;Sort the comments below BY NEW to see the latest events&lt;/p&gt;\n\n&lt;p&gt;&lt;a href="https://www.reddit.com/r/vancouver/comments/b5dlhh/april_events_and_volunteering_thread_please_post/"&gt;April Events Thread&lt;/a&gt;&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          all_awardings: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: 'google searches for you',
          visited: false,
          num_reports: null,
          distinguished: 'moderator',
          subreddit_id: 't5_2qhov',
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: '',
          id: 'bjcurx',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'soupyhands',
          num_crossposts: 0,
          num_comments: 50,
          send_replies: true,
          whitelist_status: 'all_ads',
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: 'dark',
          permalink:
            '/r/vancouver/comments/bjcurx/may_events_and_volunteering_thread_please_post/',
          parent_whitelist_status: 'all_ads',
          stickied: true,
          url:
            'https://www.reddit.com/r/vancouver/comments/bjcurx/may_events_and_volunteering_thread_please_post/',
          subreddit_subscribers: 126462,
          created_utc: 1556682932.0,
          media: null,
          is_video: false,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'vancouver',
          selftext: '',
          author_fullname: 't2_fhc4s',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title: 'Spotted in Coquitlam this morning . Be careful out there',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/vancouver',
          hidden: false,
          pwls: 6,
          link_flair_css_class: 'sand',
          downs: 0,
          thumbnail_height: 140,
          hide_score: false,
          name: 't3_bojx2w',
          quarantine: false,
          link_flair_text_color: 'dark',
          author_flair_background_color: null,
          subreddit_type: 'public',
          ups: 301,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: true,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Photo/Video',
          can_mod_post: false,
          score: 301,
          approved_by: null,
          thumbnail:
            'https://b.thumbs.redditmedia.com/2fNRoJSzaYCxg_wBJJYcmAdqD5sZnWk0sRUN1YVM-RM.jpg',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'image',
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1557874349.0,
          link_flair_type: 'text',
          wls: 6,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'i.redd.it',
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    'https://preview.redd.it/zirh0vl4x6y21.jpg?auto=webp&amp;s=6869b56247e4d488399ce3610ae0585854a21702',
                  width: 1242,
                  height: 2688,
                },
                resolutions: [
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=1142d41b89c64a9f8420b226ef96693588730116',
                    width: 108,
                    height: 216,
                  },
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=46b1da7033dc4145c2b91f7eeb753ab865118681',
                    width: 216,
                    height: 432,
                  },
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=3aeb5b08bfc6aa90ce144076e7157a4f0a89827d',
                    width: 320,
                    height: 640,
                  },
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=57ad560219268481b41891511b45f416dca4f86d',
                    width: 640,
                    height: 1280,
                  },
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=942b14cbec837a0df04cee0584257e8cc4a7fb6a',
                    width: 960,
                    height: 1920,
                  },
                  {
                    url:
                      'https://preview.redd.it/zirh0vl4x6y21.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=75e218c79a450160389a5cb8cfb0eb6eb62b3919',
                    width: 1080,
                    height: 2160,
                  },
                ],
                variants: {},
                id: 'IN0jhzER6iOc0VPTrT9P1TuuGZ562CDnKRWtUT8kcME',
              },
            ],
            enabled: true,
          },
          all_awardings: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: 't5_2qhov',
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: '',
          id: 'bojx2w',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'tobleroney69',
          num_crossposts: 0,
          num_comments: 97,
          send_replies: true,
          whitelist_status: 'all_ads',
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink:
            '/r/vancouver/comments/bojx2w/spotted_in_coquitlam_this_morning_be_careful_out/',
          parent_whitelist_status: 'all_ads',
          stickied: false,
          url: 'https://i.redd.it/zirh0vl4x6y21.jpg',
          subreddit_subscribers: 126462,
          created_utc: 1557845549.0,
          media: null,
          is_video: false,
        },
      },
      {
        kind: 't3',
        data: {
          approved_at_utc: null,
          subreddit: 'vancouver',
          selftext: '',
          author_fullname: 't2_s9mls',
          saved: false,
          mod_reason_title: null,
          gilded: 0,
          clicked: false,
          title:
            'Extensive bus-only lanes coming to 41st Avenue for new B-Line rapid bus',
          link_flair_richtext: [],
          subreddit_name_prefixed: 'r/vancouver',
          hidden: false,
          pwls: 6,
          link_flair_css_class: 'blue',
          downs: 0,
          thumbnail_height: 72,
          hide_score: false,
          name: 't3_boijsv',
          quarantine: false,
          link_flair_text_color: 'dark',
          author_flair_background_color: null,
          subreddit_type: 'public',
          ups: 189,
          total_awards_received: 0,
          media_embed: {},
          thumbnail_width: 140,
          author_flair_template_id: null,
          is_original_content: false,
          user_reports: [],
          secure_media: null,
          is_reddit_media_domain: false,
          is_meta: false,
          category: null,
          secure_media_embed: {},
          link_flair_text: 'Local News',
          can_mod_post: false,
          score: 189,
          approved_by: null,
          thumbnail:
            'https://b.thumbs.redditmedia.com/dhYQ706l8zOp01lkS4MntVLQaV8TrgQf31UTI_LwDjU.jpg',
          edited: false,
          author_flair_css_class: null,
          author_flair_richtext: [],
          gildings: {},
          post_hint: 'link',
          content_categories: null,
          is_self: false,
          mod_note: null,
          created: 1557867204.0,
          link_flair_type: 'text',
          wls: 6,
          banned_by: null,
          author_flair_type: 'text',
          domain: 'dailyhive.com',
          selftext_html: null,
          likes: null,
          suggested_sort: null,
          banned_at_utc: null,
          view_count: null,
          archived: false,
          no_follow: false,
          is_crosspostable: false,
          pinned: false,
          over_18: false,
          preview: {
            images: [
              {
                source: {
                  url:
                    'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?auto=webp&amp;s=f2f5a4fbe0049a36a5aacc04483240fabbf83a4f',
                  width: 1072,
                  height: 555,
                },
                resolutions: [
                  {
                    url:
                      'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=fe150dce5d77de3531b28ac9c38efc7069f1d4c7',
                    width: 108,
                    height: 55,
                  },
                  {
                    url:
                      'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=e4515ce6c84e3345c39a78d0237118777e6a531a',
                    width: 216,
                    height: 111,
                  },
                  {
                    url:
                      'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=a78dbe2a4469c5171af8e2b3ae58d8401aaf5083',
                    width: 320,
                    height: 165,
                  },
                  {
                    url:
                      'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=e657983ec8fcedbed82338ec7378b3b260cb006d',
                    width: 640,
                    height: 331,
                  },
                  {
                    url:
                      'https://external-preview.redd.it/0smMu4FOSdg35lXk5SL9hWUdpOYv9gwpb8LtzkJIkNo.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=ef2c7b64661e7711a64adf4d296c335b44e0519f',
                    width: 960,
                    height: 497,
                  },
                ],
                variants: {},
                id: 'A_SbCSaj4JVNuViU-ZOr4UDrWMmbX25VqvhqLwmGvnI',
              },
            ],
            enabled: false,
          },
          all_awardings: [],
          media_only: false,
          can_gild: false,
          spoiler: false,
          locked: false,
          author_flair_text: null,
          visited: false,
          num_reports: null,
          distinguished: null,
          subreddit_id: 't5_2qhov',
          mod_reason_by: null,
          removal_reason: null,
          link_flair_background_color: '',
          id: 'boijsv',
          is_robot_indexable: true,
          report_reasons: null,
          author: 'RockMe-Amadeus',
          num_crossposts: 0,
          num_comments: 60,
          send_replies: true,
          whitelist_status: 'all_ads',
          contest_mode: false,
          mod_reports: [],
          author_patreon_flair: false,
          author_flair_text_color: null,
          permalink:
            '/r/vancouver/comments/boijsv/extensive_busonly_lanes_coming_to_41st_avenue_for/',
          parent_whitelist_status: 'all_ads',
          stickied: false,
          url:
            'https://dailyhive.com/vancouver/41st-avenue-b-line-street-changes-route',
          subreddit_subscribers: 126462,
          created_utc: 1557838404.0,
          media: null,
          is_video: false,
        },
      },
    ],
    after: 't3_boo8gn',
    before: null,
  },
}
